### ISSUE TITLE
While parsing a protocol message, the input ended unexpectedly in the middle of a field.

### ISSUE THREAD

**Issue by cecol** [os72/protobuf-dynamic#1]
First of all, thank you for your contribution
The problem is
I want to build protobuf schema from .proto file
I use your DynamicSchema to build schema then use the schema to parse a byte message which is generated by precompiled protobuf java class 
but I get the following exception:
While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

this is my code : https://github.com/cecol/protobuf-to-avro/blob/dev/src/main/java/wilber/com/transform/Main.java
is any misunderstand of your DynamicSchema or any mistake in my code?

**Comment by os72** [comment]
You're just missing the last step to create a message builder from the schema. This is a regular protobuf DynamicMessage builder you can use to parse the byte array
```
DynamicMessage.Builder msgBuilder = personSchema.newMessageBuilder("Person");
DynamicMessage msg = msgBuilder.mergeFrom(john.toByteArray()).build();
```

For the .proto parsing you could use https://github.com/square/protoparser

**Comment by cecol** [comment]
Cool !!!
Thank you very much, I could parse message from dynamic schema
and the .proto file parser of  https://github.com/square/protoparser is very helpful
I can keep working my project!!
