### ISSUE TITLE
While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.

### ISSUE THREAD

**Issue by mahendratonape** [os72/protobuf-dynamic#10]
Hi,
I had written producer, consumer application, here producer thread produces messages, serializes it with protobuff and publishes it with zeroMQ publisher.
At consumer side thread will subscriber on zeroMQ port and deserializes the messsages with protobuff. I am getting below issues randomly at my consumer side while decoding protobuff byte array: 
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	
[ProtobuffIssues12HrsTest.txt](https://github.com/os72/protobuf-dynamic/files/2722829/ProtobuffIssues12HrsTest.txt)

These issues i am getting is random issue it's not that i am getting it for each and every message, out of 47,00,000 messages in 12hrs i got this issue for 10 messages, and i am testing this on a single machine.

Below is my producer proto file:-
[ProtoFileProducer1.txt](https://github.com/os72/protobuf-dynamic/files/2722897/ProtoFileProducer1.txt)

Below is my producer class:-
[Producer.txt](https://github.com/os72/protobuf-dynamic/files/2722898/Producer.txt)

Below is my consumer proto file:-
[ConsumerProtoFile.txt](https://github.com/os72/protobuf-dynamic/files/2722899/ConsumerProtoFile.txt)

Below is my consumer class:
[Consumer.txt](https://github.com/os72/protobuf-dynamic/files/2722900/Consumer.txt)

**Comment by os72** [comment]
Doesn't sound like a protobuf-dynamic issue, are you actually using it?

**Comment by os72** [comment]
Assuming closed

**Comment by Greatsamps** [comment]
> Hi,
> I had written producer, consumer application, here producer thread produces messages, serializes it with protobuff and publishes it with zeroMQ publisher.
> At consumer side thread will subscriber on zeroMQ port and deserializes the messsages with protobuff. I am getting below issues randomly at my consumer side while decoding protobuff byte array:
> com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either that the input has been truncated or that an embedded message misreported its own length.
> 
> [ProtobuffIssues12HrsTest.txt](https://github.com/os72/protobuf-dynamic/files/2722829/ProtobuffIssues12HrsTest.txt)
> 
> These issues i am getting is random issue it's not that i am getting it for each and every message, out of 47,00,000 messages in 12hrs i got this issue for 10 messages, and i am testing this on a single machine.
> 
> Below is my producer proto file:-
> [ProtoFileProducer1.txt](https://github.com/os72/protobuf-dynamic/files/2722897/ProtoFileProducer1.txt)
> 
> Below is my producer class:-
> [Producer.txt](https://github.com/os72/protobuf-dynamic/files/2722898/Producer.txt)
> 
> Below is my consumer proto file:-
> [ConsumerProtoFile.txt](https://github.com/os72/protobuf-dynamic/files/2722899/ConsumerProtoFile.txt)
> 
> Below is my consumer class:
> [Consumer.txt](https://github.com/os72/protobuf-dynamic/files/2722900/Consumer.txt)

did you ever find the solution to this issue? we too are getting random errors such as this...
