### ISSUE TITLE
make DynamicSchema.mFileDescSet accessible

### ISSUE THREAD

**Issue by jhsenjaliya** [os72/protobuf-dynamic#14]
can we provide getmFileDescSet() ? currently its private so its not accessible.

**Comment by os72** [comment]
Ack. Simple enough, just need to make some time. Would you be interested to submit a PR?
Also, could you share your usecase? DynamicSchema is mostly there to abstract FileDescriptorSet :)

**Comment by jhsenjaliya** [comment]
sure, I already made change and been using it, its really required if we want to convert to JSON.  Thanks

**Comment by jhsenjaliya** [comment]
here you go. #15 
please let me know if you need any help. Thanks.

**Comment by jhsenjaliya** [comment]
@os72 pls take a look. pls also release the library 1.0.1 that i can fetch and use. Thanks

**Comment by os72** [comment]
Ack, yes. Note I'll probably adjust the getter names to stay consistent
(BTW if this is for PayPal, please consider sponsoring, thanks)

**Comment by os72** [comment]
I kept getFileDescriptorSet(). getMessageTypes()/getEnumTypes() was already there
Does this work: https://github.com/os72/protobuf-dynamic/commit/bbcf3391fc8408b76870e6d3d1775faafa04fdc5

**Comment by jhsenjaliya** [comment]
I am actually trying to add protobuf schema registry in hortonworks schema reg., would like to get your feedback on that once done.

**Comment by os72** [comment]
Released 1.0.1, 0.9.5

**Comment by os72** [comment]
@jhsenjaliya I pinged you on email, not sure it went through

**Comment by jhsenjaliya** [comment]
Sure, responded over email. Thanks
