### ISSUE TITLE
add way to find current msgTypeNames in DynamicSchema

### ISSUE THREAD

**Issue by hepin1989** [os72/protobuf-dynamic#3]
I think add way to inspect/iterator current msgTypeNames lives in DynamicSchema would be helpful.

**Comment by os72** [comment]
This is trivial to implement, but what would you do with the information? If it's just for debugging, note that toString() provides it

**Comment by hepin1989** [comment]
Yes,I mean you keep it private,but anyway I have collect information from somewhere else,so If you want to expose it,then could expose the keys,otherwise close this issue.

**Comment by os72** [comment]
So your application requires this information? I can add getters no problem, returning:
`Set<String> msgTypes = new TreeSet<String>(mMsgDescriptorMapFull.keySet())`

**Comment by hepin1989** [comment]
yes,that exactly what I mean,btw,thanks for this project,very helpful.

**Comment by os72** [comment]
released 0.9.3
