### ISSUE TITLE
[feature request] Java IDL for protobuf (Protocl Buffers in Java)

### ISSUE THREAD

**Issue by paulvi** [os72/protobuf-dynamic#6]
well, I think if it ever appear, it will come with your participation: 

Java IDL for protobuf (Protocl Buffers in Java)

That is instead of 

    service Greeter {
      rpc SayHello (HelloRequest) returns (HelloReply) {}
    }

I would like to have

    public interface Greeter {
    	@Grpc
    	HelloReply sayHello (HelloRequest req);
    
    }
    
    @GrpcMessage()
    public class HelloReply{
    	@GrpcField(1)
    	string name;
    } 

That is annotation like Hibernate/JPA over my POJO, instead of heaps of generated code.

http://stackoverflow.com/questions/40425211/java-idl-for-protobuf-protocl-buffers-in-java

**Comment by os72** [comment]
Have a look at protostuff: https://github.com/protostuff/protostuff
It supports what you want for protobuf (although not for grpc)
